version: '3.7'

services:
  nginx:
    image: nginx:1.15-alpine
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
      labels:
        - "traefik.frontend.rule=Host:test-brillonline.semce.net"
        - "traefik.port=443"
        - "traefik.docker.network=traefik_traefik"
      replicas: 1
      placement:
        constraints:
          - node.labels.brillonline == true
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - brill-certbot-conf:/etc/letsencrypt
      - brill-certbot-www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    configs:
      - source: nginx-app
        target: /etc/nginx/conf.d/app.conf
  certbot:
    image: certbot/certbot
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
      replicas: 1
      placement:
        constraints:
          - node.labels.brillonline == true
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - brill-certbot-conf:/etc/letsencrypt
      - brill-certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

configs:
  nginx-app:
  external: true

volumes: 
  brill-certbot-conf: 
  brill-certbot-www:

networks:
  traefik_traefik:
    driver: overlay
    external: true
